# Generated by Django 3.0.5 on 2020-04-10 04:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0004_hr_reg'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vacancy', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=100)),
                ('hr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HR.HR_Reg')),
            ],
        ),
    ]
