# Generated by Django 3.0.5 on 2020-04-10 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0005_vacancy'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='status',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
