# Generated by Django 3.0.5 on 2020-04-10 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0006_vacancy_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apply_Vacancy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cv', models.ImageField(upload_to='images/')),
                ('status', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HR.Applicant_Reg')),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HR.Vacancy')),
            ],
        ),
    ]
