# Generated by Django 3.0.5 on 2020-04-10 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0007_apply_vacancy'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=100)),
                ('time', models.CharField(max_length=100)),
                ('apply', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HR.Apply_Vacancy')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HR.Applicant_Reg')),
            ],
        ),
    ]
