# Generated by Django 3.0.5 on 2020-04-10 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0008_interview'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interview',
            name='user',
        ),
    ]
