# Generated by Django 3.0.5 on 2020-04-10 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0010_accept_app'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accept_app',
            name='vacancy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HR.Apply_Vacancy'),
        ),
    ]
