# Generated by Django 3.0.5 on 2020-04-11 06:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('HR', '0011_auto_20200410_2135'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empid', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('fname', models.CharField(max_length=100)),
                ('dob', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=100)),
                ('religion', models.CharField(max_length=100)),
                ('bloodgroup', models.CharField(max_length=100)),
                ('maritalstatus', models.CharField(max_length=100)),
                ('nationality', models.CharField(max_length=100)),
                ('mob', models.CharField(max_length=100)),
                ('presentadd', models.CharField(max_length=100)),
                ('permanentadd', models.CharField(max_length=100)),
                ('moderecuirt', models.CharField(max_length=100)),
                ('dateofjoin', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('reportingboss', models.CharField(max_length=100)),
                ('cv', models.CharField(max_length=100)),
                ('basicsalary', models.CharField(max_length=100)),
                ('salaryperday', models.CharField(max_length=100)),
                ('accept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HR.Accept_App')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
