# Generated by Django 3.0.5 on 2020-04-11 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0012_employee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='name',
        ),
    ]
