# Generated by Django 3.0.5 on 2020-04-11 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0013_remove_employee_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='cv',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='salaryperday',
        ),
    ]
