# Generated by Django 3.0.5 on 2020-04-11 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0014_auto_20200411_1607'),
    ]

    operations = [
        migrations.AddField(
            model_name='accept_app',
            name='status',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='interview',
            name='status',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
