# Generated by Django 3.0.5 on 2020-04-11 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0016_employee_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interview',
            name='status',
        ),
    ]
