# Generated by Django 3.0.5 on 2020-04-11 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0017_remove_interview_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='status',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
