# Generated by Django 3.0.5 on 2020-04-13 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0019_leave'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='status',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
