# Generated by Django 3.0.5 on 2020-04-14 04:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0020_leave_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmpAttandance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HR.Employee')),
            ],
        ),
    ]
