# Generated by Django 3.0.5 on 2020-04-14 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0023_auto_20200414_2044'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddWorkStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=100)),
                ('photo', models.ImageField(upload_to='images/')),
                ('status', models.CharField(max_length=100)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HR.Employee')),
            ],
        ),
    ]
