# Generated by Django 3.0.5 on 2020-04-15 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0025_addworkstatus_addwork'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addworkstatus',
            name='employee',
        ),
    ]
