# Generated by Django 3.0.5 on 2020-04-15 08:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0027_addwork_hr'),
    ]

    operations = [
        migrations.AddField(
            model_name='empattandance',
            name='hr',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='HR.HR_Reg'),
        ),
    ]
