# Generated by Django 3.0.5 on 2020-04-15 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0028_empattandance_hr'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=100)),
                ('attendance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HR.EmpAttandance')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HR.Employee')),
                ('hr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HR.HR_Reg')),
            ],
        ),
    ]
