# Generated by Django 3.0.5 on 2020-04-17 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0033_attreport_gdate'),
    ]

    operations = [
        migrations.CreateModel(
            name='HrReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noemployee', models.CharField(max_length=100)),
                ('noworks', models.CharField(max_length=100)),
                ('hr', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='HR.HR_Reg')),
            ],
        ),
    ]
