# Generated by Django 3.0.5 on 2020-04-18 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0034_hrreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='hrreport',
            name='date',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
